# Generated by Django 2.2.dev20181116200922 on 2018-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.IntegerField(default=2000, verbose_name='grade'),
        ),
    ]
