# Generated by Django 2.2.dev20181116200922 on 2018-12-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0003_auto_20181223_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.IntegerField(default=4, verbose_name='grade'),
        ),
    ]
