# Generated by Django 2.1.4 on 2018-12-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0006_auto_20181229_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(verbose_name='availability'),
        ),
    ]
