# Generated by Django 2.1.4 on 2018-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0008_auto_20181229_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(default=4, verbose_name='grade'),
        ),
    ]
