# Generated by Django 2.1.4 on 2019-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbr', '0013_auto_20190222_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avatar',
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
